### ISSUE TITLE
Update from 2.4.9 GitHub to 2.5.1 - updateQuickBox fails

### ISSUE THREAD

**Issue by asafsarid** [QuickBox/QB#10]
When running the following in order to upgrade to 2.5.1:

```
wget -O /usr/local/bin/quickbox/system/updateQuickBox https://raw.githubusercontent.com/QuickBox/QB/master/packages/system/updateQuickBox &&
dos2unix $(find /usr/local/bin/quickbox -type f) && chmod +x $(find /usr/local/bin/quickbox -type f)
updateQuickBox
```

I am getting the following errors:
```
/usr/local/bin/quickbox/system/updateQuickBox: line 456: v: command not found
mv: cannot stat 'rtorrent': No such file or directory
/usr/local/bin/quickbox/system/updateQuickBox: line 460: syntax error near unexpected token `fi'
/usr/local/bin/quickbox/system/updateQuickBox: line 460: `  fi'
```

Seems that other users have this issue as well: https://plaza.quickbox.io/t/combined-repo-and-qb-version-problem/3092/14

**Comment by verttex** [comment]
This issue should be resolved with the commands that were listed in the forums after my own post:

`rm -rf /etc/QuickBox
git clone https://github.com/QuickBox/QB /etc/QuickBox`

This should fix your issue, but it still means that the upgrade instructions are not working. Seems most of us should just go through the regular installation instructions.

**Comment by JMSDOnline** [comment]
README on GitHub as well as the FAQ on the site have been updated to make this as clear as possible.

https://github.com/QuickBox/QB/commit/c22c5f5e4556c7965a84f9c98f60aed4b97d0b7a
