### ISSUE TITLE
Blank screen after update and change to spanish

### ISSUE THREAD

**Issue by JuezFenix** [QuickBox/QB#104]
Hi,

Few minutes ago, I update quickbox, when I change language to spanish, a white screen are the only that I saw.

Edit: Manualy I recover web interface, changing require "($_SERVER['DOCUMENT_ROOT']."/lang/lang_es");" to "require ($_SERVER['DOCUMENT_ROOT']."/lang/lang_en");" but of course, interface are in english.

Thanks.

**Comment by Meiden-fc** [comment]
Sorry, that's my fault. There was a mistake in syntax in the lang_es file. I've already updated it, and I've made the pertinent pull request. We just need to wait until an admin accepts it and after that you'll be able to set spanish language with no further issues.

Sorry mate.

**Comment by JuezFenix** [comment]
Don't worry friend, at least was a simple thing. Many thanks for fast aswer an for the efford to translate all.

Should be extrange after so many time using it to see all in my language jeje

**Comment by Meiden-fc** [comment]
Pull request was merged, so Spanish language is working like a charm right now.

This issue can be close :D

**Comment by JuezFenix** [comment]
Many thanks.
