### ISSUE TITLE
transmission issue?

### ISSUE THREAD

**Issue by alexzapatka** [QuickBox/QB#105]
transmission does not appear to be hidden behind the apache reverse proxy.  at least on my (bra>nd new seed box, just installed the latest version of quickbox)  i can reach transmission 2 ways:

https://<server.ip>/transmission/web (i get a million new log in prompts too)
AND
http://<server.ip>:9091/transmission/web

**Comment by JMSDOnline** [comment]
I did get two login prompts, one on the dashboard and one within transmission. I should be able to adjust an .htaccess file to sort this out. However, after the two login prompts, the reverse works just fine.

Anyone else hitting this?

**Comment by JMSDOnline** [comment]
Closing as no additional feedback has been given.
