### ISSUE TITLE
Outdated version of SickRage

### ISSUE THREAD

**Issue by Anthodev** [QuickBox/QB#106]
Hello,

I wanted to point out that the repo used for SickRage is outdated since a while. The active repo is located on GitLab since a while: https://git.sickrage.ca/SiCKRAGE/sickrage

Can you update the installation package, modifying the url of the repo doesn't seem to be enough to make it work.

Thanks! :)

**Comment by JMSDOnline** [comment]
Apologies on the delay for this, just pushed https://github.com/QuickBox/QB/commit/145a8dc106fe461257c78ef2545a398c67c35403 to address this. Thank you @Anthodev for pointing this out! 👍
