### ISSUE TITLE
Usage of submodules

### ISSUE THREAD

**Issue by Dantrum** [QuickBox/QB#109]
Is it possible to make use of sub modules to keep external maintained repositories updated in QuickBox ? ruTorrent for example seems to be slacking behind.

**Comment by JMSDOnline** [comment]
ruTorrent has been updated in the script. The only other thing that has been ported to the community version is the plugin updates, mainly just the addition of `spectrogram`. I had used submodules and even pulled directly from the author repo before, however, submodules are cumbersome for those that don't have a good grasp on `git` that would like to contribute, and maintaining the repo for ruTorrent on my end just makes support easier.
