### ISSUE TITLE
Ombi is missing libunwind8

### ISSUE THREAD

**Issue by splifter** [QuickBox/QB#110]
I've installed Ombi via the QB dashboard but it didn't start.
So i've investigated and the package libunwind8 was missing. Which is strange because it's in the [dependencies of the install script](https://github.com/QuickBox/QB/blob/master/packages/package/install/installpackage-ombi). But i was able to reproduce this issue, therefore i want to mention it here.

After installing it via
> sudo apt-get install libunwind8

Ombi started as expected.

**Comment by gaastra2-44** [comment]
On clean install and after testing twice reinstalling it, Ombi won't start, stay locked on "Loading page". This won't solve the problem on my side, package is up to date.

**Comment by splifter** [comment]
Did you restarted ombi?
> service ombi restart
What does:
> service ombi status
say?

**Comment by JMSDOnline** [comment]
Fixed here https://github.com/QuickBox/QB/commit/fe1a2fdf189060f67722a20d814dced53b123698
