### ISSUE TITLE
Rutorrent Access Frozen on users ( not the main )

### ISSUE THREAD

**Issue by Whisper40** [QuickBox/QB#122]
Hi, I just installed a brand new Ubuntu 16.04 HETZNER server.
I'm on an I7 2600 - 16 GB RAM, 14 TB server and
 I'm experiencing a huge delays of access to rutorrent, the page takes more than 30 seconds to be displayed and after the display it lag.. the page is loading and loading....

The interface is really lagging after 3 minutes ! : 
http://prntscr.com/ilfp5e
http://prntscr.com/ilfpz5

**Comment by Whisper40** [comment]
Google Chrome was causing the problem...
Thanks Firefox :)

**Comment by Zeldri** [comment]
What offer did you take on HETZNER ???

**Comment by Whisper40** [comment]
I have 3 servers , I7 2600 16Go   14 To
