### ISSUE TITLE
Mono 5.10 now possible, Jackett, Sonarr, Radarr updated

### ISSUE THREAD

**Issue by Wyall** [QuickBox/QB#124]
Radarr just released the update to work with Mono 5.10 and Jackett and Sonarr already did this a few days ago.
I think now Mono 5.10 can be used or the most current version, as right now it's set to 5.8 I think (because of the problems with Mono 5.10)

**Comment by whalingman** [comment]
Weirdly I'm running Mono 4.2.1. Unsure why it hasn't been updated on my end. Running web updater doesn't seem to update it...

**Comment by Wyall** [comment]
Mono doesn't get updated via web updater I think, only via apt upgrade. This is the fix that can be reverted:
https://github.com/QuickBox/QB/commit/03b7a92e2a0d684d1fbdb3e26985fb408c710075
It just changed what mono version gets installed on new installs of QB as the version is specified, and not just the newest version available

**Comment by JMSDOnline** [comment]
Testing this now with current mono libraries. I will publish in the "web Updater" a revision on the sources.list later today.

Thank you for the update! 😄
