### ISSUE TITLE
Quota disk showing blank after update

### ISSUE THREAD

**Issue by nerull13** [QuickBox/QB#126]
hi every one ,

first of all i want to say that i tried all fix command but nothing …

I updated my 2.5.3 with new commits on the dashboard updater . And then i have blank quota
Before it was ok

/etc/fstab
```
UUID=4422b764-6c18-4f0c-9de4-a44367b6013d / ext4 usrjquota=aquota.user,jqfmt=vfsv1,errors=remount-ro 0 1
# /boot was on /dev/sda1 during installation
UUID=f3ee580a-147b-4f12-be39-7085fe4216d9 /boot ext4 defaults 0 2
# swap was on /dev/sda2 during installation
UUID=6316f729-9ffb-4f1d-afdd-9374d9d5b9ba none swap sw 0 0

```
LSBLK :
```
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda 8:0 0 1.8T 0 disk
├─sda2 8:2 0 1G 0 part [SWAP]
├─sda3 8:3 0 1.8T 0 part /
└─sda1 8:1 0 199M 0 part /boot

```
so i did : fix-disk_widget_root and then setdisk

still same problem

If i uninstall quota , the full disk size is showing ! with quota its blank : You have used NaN% of your total disk space

i rememder that in home folder it was supposed to be a file with the quota but not sure

Could be really nice to have some help !! Please !

**Comment by Whisper40** [comment]
Hello, i was having the same issue, i solved it by doing that.
If that don't work i don't have idea

chmod 755 /home/%USER%
chown %USER%:www-data /home/%USER%/torrents/rtorrent

**Comment by nerull13** [comment]
thx for your response.    

still blank :(
