### ISSUE TITLE
Does removing CSF reinstall the fail2ban?

### ISSUE THREAD

**Issue by danjames92** [QuickBox/QB#129]
By default quickbox sets up fail2ban and rules for it. 

When install CSF, it gets uninstalled and doesn't appeared to be reinstall when removing CSF.

Feature request? Is there a way to manually get fail2ban back on there?

(would ask on the forum but my account is blocked (for no reason) and i can't reset the password for some stupid reason)

**Comment by JMSDOnline** [comment]
> By default quickbox sets up fail2ban and rules for it.
QuickBox by default, only installs fail2ban, it doesn't set up rules. This is only the case with CSF.. basic and looking at it now, needs a few items updated.

> When install CSF, it gets uninstalled and doesn't appeared to be reinstall when removing CSF.
Interesting, is this saying that on install it is not installing, rather removing things. 😕 

> Feature request? Is there a way to manually get fail2ban back on there?
You can do `apt-get install fail2ban`. Again, QuickBox doesn't install rules for this at the moment.

> (would ask on the forum but my account is blocked (for no reason) and i can't reset the password for some stupid reason)
Hmm, I don't see any block on your account, nor attempts to login (only checking for troubleshooting). Could you email `echo@quickbox.io` to have this resolved?

**Comment by spider1163** [comment]
Hello,
Does the QB script only install fail2ban without modification ?
So there is no fail2ban on custom SSH port for example ?

**Comment by JMSDOnline** [comment]
> Does the QB script only install fail2ban without modification ?
Correct, it makes no additional changes.

> So there is no fail2ban on custom SSH port for example ?
Correct
