### ISSUE TITLE
pyLoad not working after install 

### ISSUE THREAD

**Issue by P4TR1** [QuickBox/QB#14]
`(1:501)#` `setup-pyLoad`
`/usr/bin/python: can't open file /home/<user>/.pyload/pyLoadCore.py: [Errno 2] No such file or directory`

**Comment by JMSDOnline** [comment]
Addressed this and confirmed working as per this push: https://github.com/QuickBox/QB/commit/dd253fa0e22d5da0754ae8da72a47bb918359a78

We were pulling the `master` repo and not adding a flag to clone the `stable`.
