### ISSUE TITLE
Add Package Lidarr

### ISSUE THREAD

**Issue by Petr0s92** [QuickBox/QB#146]
https://github.com/lidarr/Lidarr

Like Headphones for downloading music, Looks and smells like Sonarr but made for music.

**Comment by Hostground** [comment]
+1 for this

**Comment by KaraokeStu** [comment]
I have (hopefully) created the right package here now :)

https://github.com/QuickBox/QB/pull/147

**Comment by JMSDOnline** [comment]
Added. Thank you @KaraokeStu
