### ISSUE TITLE
Tautulli

### ISSUE THREAD

**Issue by Rewels** [QuickBox/QB#155]
Since the new release, PlexPy disappeared from the list so had to reinstall Tautulli but the link on the left side no longer works and loops back to Quickbox, also missing image for Tautulli icon.

Status icon for Tautulli is missing in Service Control Center.

Just wondering if anyone knows how to fix this

Many Thanks,
Kyle

**Comment by Rewels** [comment]
Okay I managed to fix the link with the Override PHP file that I use, however the icon doesn't work still not a major issue of course!

**Comment by Rewels** [comment]
Fixed icon by adding image to /srv/rutorrent/home/img/brands/

Status icon on Service Control Center would be nice to have working again though.

**Comment by Rewels** [comment]
Status icon seems to be working now after making some changes to the image files

**Comment by Bybou** [comment]
Can you please explain to me/us what do you mean by :

> I managed to fix the link with the Override PHP file that I use

Because i have exactly your issue and for the moment only the old link is working "https:xxxxx/plexpy"
And "https:xxxxx/tautulli" is not working.

Thanks

**Comment by Rewels** [comment]
The Override PHP file I put place to fix the plex link because I setup a plex.domain.com.

I had to go via SSH to remove PlexPy using box remove plexpy and then reinstall using Tautulli, this then puts a new icon the quickbox menu and links via /tautulli.
