### ISSUE TITLE
unable to create new user

### ISSUE THREAD

**Issue by ctrlx83** [QuickBox/QB#188]
Hi everyone,

I can't to create a new user with SeedBox

I try with the command sudo createSeedboxUser
shel always answer command not found

thanks for your help !

**Comment by tomcdj71** [comment]
Hey ! Are you running as root or as user ?
To be sure please, do the following : 

`sudo su -` (the dash is very, very important)

`createSeedboxUser`

Then you'll be able to create an user

Kind Regards

**Comment by ctrlx83** [comment]
perfect !

thanks a lot
