### ISSUE TITLE
Seeing clearly 

### ISSUE THREAD

**Issue by ghost** [QuickBox/QB#195]
reusables/README.md

 # clone
    git clone https://github.com/codefont --depth=1
    # install
    cd fonts
    ./install.sh
        windows  run windowsinstall shell
    # clean-up a bit
    cd ..
    rm -rf fonts
[Open] Bug Report Problems

- orcal_c=+4-1("snoopy"):. uninstalling sourceless tweak.

[Open] Bug Report Problems

 uninstalling sourceless tweak.

**Comment by rcgoodstuf** [comment]
> reusables/README.md
> 
>  # clone
>     git clone https://github.com/codefont --depth=1
>     # install
>     cd fonts
>     ./install.sh
>         windows  run windowsinstall shell
>     # clean-up a bit
>     cd ..
>     rm -rf fonts

Hello.("Reel_Rook"):

**Comment by MaximeMichaud** [comment]
?

**Comment by JMSDOnline** [comment]
No relevance or additional info given as to what this is. Wrong project perhaps?
