### ISSUE TITLE
Incorrect uptime and disk usage on Debian 8

### ISSUE THREAD

**Issue by k0nsl** [QuickBox/QB#2]
The uptime and disk usage is incorrectly displayed for Debian 8 (and in the case of disk usage -- not displayed at all), see:

https://f.0x0f.su/n7tSLUMhlWNVtFK_Selection_023.jpg

Meanwhile the actual output of `uptime` is:
```
QuickBox01:~# uptime
 02:57:55 up 4 min,  2 users,  load average: 5.94, 6.39, 6.62
```
I am running QB version `2.5.0`. If you need anything else, let me know and I will try to do my best in order to help.

**Comment by JMSDOnline** [comment]
It's possible you need to refresh your page as sometimes the widgets can 'freeze' after the page has been loaded for some time. As per your disk usage, we have plenty of resources on the forums to address this as it is 100% normal. If you are utilizing Quotas you will need to use the `setdisk` command to arrange space for the user... if you have activated the widget on the wrong mount then run either the...

```
fix-disk_widget_home
```
or
```
fix-disk_widget_root
```

According to whichever your mount is. You can find it via `lsblk`

**Comment by k0nsl** [comment]
Thank you,  @JMSDOnline. I will try running the commands for fixing the disk widget. As for the uptime, I have in fact been refreshing the page and also cleared the cache to no avail. It reports the same value.

Incidentally I noticed something odd as I was running `bench.sh` (i.e https://github.com/k0nsl/k0nsl-misc/blob/master/bench.sh) and it reported the same faulty value for uptime which QB reports. And that is very odd since the script runs just fine on my other LXC containers and reports back the correct values.
Here is what the script reported:
```
Colormedia Benchmark 0.1/a (forked by k0nsl)
Website  : k0nsl.org
Contact  : irc.k0nsl.org #k0nsl

General Information 

CPU :  Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
CPU Cores :  8
CPU frequency per core :  3399.867 MHz
Memory : 2096 MB
Swap Space : 1096 MB
Uptime : 0 days, 0 hours, 3 minutes
Kernel : 4.4.35-2-pve

Network Benchmark 

Download Speed:  BuyVM (US): 12.2MB/s 
Download Speed:  DigitalOcean (US): 24.7MB/s 
Download Speed:  RamNode (US): 19.7MB/s 
Download Speed:  Incero (US): 22.0MB/s 
Download Speed:  Dacentec (USA): 64.4MB/s 
Download Speed:  HostHatch (EU): 16.0MB/s 
Download Speed:  DigitalOcean (EU): 18.7MB/s 
Download Speed:  RamNode (EU): 22.0MB/s 
Download Speed:  BuyVM (EU): 18.6MB/s 
Download Speed:  YourServer (EU): 4.72MB/s 

Disk Benchmark

I/O Performance [1]:  66.3 MB/s
I/O Performance [2]:  70.2 MB/s
I/O Performance [3]:  78.5 MB/s
```

And when I run `uptime` directly after:
```
 09:47:07 up 7 min,  2 users,  load average: 4.19, 4.36, 4.13
```

I don't understand what could possibly cause such a thing. I haven't seen that before, IIRC.

Anyway, thanks for the help.

[EDIT: running either `fix-disk_widget_home` or `fix-disk_widget_root` didn't solve the blank disk space widget; I will report back later today and see if a reboot solves it.]

**Comment by k0nsl** [comment]
Thank you, @JMSDOnline. I will try running the commands for fixing the disk widget. As for the uptime, I have in fact been refreshing the page continuously and I also cleared the cache to no avail. It reports the same value.

Incidentally I noticed something odd as I was running `bench.sh` (i.e https://github.com/k0nsl/k0nsl-misc/blob/master/bench.sh) and it reported the same faulty value for uptime which QB reports. And that is very odd since the script runs just fine on my other LXC containers and reports back the correct values. That is true both for containers on the same server and on containers running on servers in completely different data centers.
Here is what the script reported:
```
Colormedia Benchmark 0.1/a (forked by k0nsl)
Website  : k0nsl.org
Contact  : irc.k0nsl.org #k0nsl

General Information 

CPU :  Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
CPU Cores :  8
CPU frequency per core :  3399.867 MHz
Memory : 2096 MB
Swap Space : 1096 MB
Uptime : 0 days, 0 hours, 3 minutes
Kernel : 4.4.35-2-pve

Network Benchmark 

Download Speed:  BuyVM (US): 12.2MB/s 
Download Speed:  DigitalOcean (US): 24.7MB/s 
Download Speed:  RamNode (US): 19.7MB/s 
Download Speed:  Incero (US): 22.0MB/s 
Download Speed:  Dacentec (USA): 64.4MB/s 
Download Speed:  HostHatch (EU): 16.0MB/s 
Download Speed:  DigitalOcean (EU): 18.7MB/s 
Download Speed:  RamNode (EU): 22.0MB/s 
Download Speed:  BuyVM (EU): 18.6MB/s 
Download Speed:  YourServer (EU): 4.72MB/s 

Disk Benchmark

I/O Performance [1]:  66.3 MB/s
I/O Performance [2]:  70.2 MB/s
I/O Performance [3]:  78.5 MB/s
```
(NOTE: upon closer inspection there was nothing ‘odd’ or ‘peculiar’ about the output from the above benchmark; my eyes were just tired due to lack of sleep.)

And when I run `uptime` directly after, it shows:
```
 09:47:07 up 7 min,  2 users,  load average: 4.19, 4.36, 4.13
```

I don't understand what could possibly cause such a thing. I haven't seen that before, IIRC.

Anyway, thanks for the help.

[EDIT #1: running either `fix-disk_widget_home`, `fix-disk_widget_root` or `setdisk` didn't solve the issue with the panel/widget showing empty/blank disk space. I will report back later today and see if a reboot solves it.]

[EDIT #2: rebooting the container did not solve the issue, either.]

[EDIT #3: the only issue now is the widget which returns nil for disk space usage -- the uptime is being correctly displayed, that was just a stupid human error caused by lack of sleep, but the other issue is very real.]

**Comment by JMSDOnline** [comment]
1. What is the output of `lsblk`?
2. Use our [Forums](https://plaza.quickbox.io)!
3. Do you have Quota installed?
4. Use our [Forums](https://plaza.quickbox.io)!

**Comment by k0nsl** [comment]
`lsblk` shows:

```
QuickBox01:/home/k0nsl# lsblk
lsblk: dm-0: failed to get device path
lsblk: dm-1: failed to get device path
lsblk: dm-2: failed to get device path
lsblk: dm-3: failed to get device path
lsblk: dm-0: failed to get device path
lsblk: dm-1: failed to get device path
lsblk: dm-2: failed to get device path
lsblk: dm-3: failed to get device path
lsblk: dm-4: failed to get device path
lsblk: dm-5: failed to get device path
lsblk: dm-6: failed to get device path
lsblk: dm-7: failed to get device path
lsblk: dm-8: failed to get device path
lsblk: dm-9: failed to get device path
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 223.6G  0 disk 
├─sda1   8:1    0  1007K  0 part 
├─sda2   8:2    0   127M  0 part 
└─sda3   8:3    0 223.5G  0 part 
sdb      8:16   0   1.8T  0 disk 
└─sdb1   8:17   0   1.8T  0 part 
loop0    7:0    0    10G  0 loop 
loop1    7:1    0   130G  0 loop 
loop2    7:2    0   100G  0 loop 
loop3    7:3    0     8G  0 loop 
loop4    7:4    0     8G  0 loop 
loop5    7:5    0    18G  0 loop 
loop6    7:6    0   500G  0 loop /
```

And yes, I have quota installed. I'll use the forums if I run into further issues.

Thanks for providing QB. I like it a lot.
