### ISSUE TITLE
Ombi false status (minor issue)

### ISSUE THREAD

**Issue by JzJad** [QuickBox/QB#22]
Dash show's Ombi as being offline/down, even when it's up.

**Comment by JMSDOnline** [comment]
You're more than likely having this issue as a result of upgrading from a previous version of QuickBox that used PlexRequests. You can more than likely just run `upgradeOmbi` to solve this issue as it will backup your old database and rename them accordingly. One of the unfortunate side-effects of QuickBox being able to handle so many applications, is that when a name change occurs, it can complicate things.

**Comment by JzJad** [comment]
Oh I'm well aware of the problems that come with a frontend like this, and I must say you guys are doing an absolutely great job, also I performed the upgradeOmbi rebooted just in case and it persists, minor like I said not worried about it, I will be reporting some of the more important bugs here soon, once I run into them again.
