### ISSUE TITLE
Editing install scripts in Quickbox

### ISSUE THREAD

**Issue by userdocs** [QuickBox/QB#28]
I edited an install script then install an app from the dashboard. From that point onwards no matter what I do the install script seems to use the first version and no changes are reflected in the dashboard installation.

How to I modify and test installation scripts in Quickbox so that i can edit and test modifications?

Is it cached or moved somewhere? I tried clear mem, rebooting and so but nothing seems to work. I am just stuck with the original edited version.

**Comment by d2dyno** [comment]
This sounds more like a forums post...

But anyways. Are you editing bash.rc? Or are you talking about a non-core install script? If it's one of the app installs, are you editing the files in /usr/local/bin/quickbox/package/install?

**Comment by userdocs** [comment]
Ok thanks, I'll use the forum for similar questions next time.

I was indeed editing the wrong location in `/etc/Quickbox/`

But what really threw me was not understanding how output is directed to the web console using `>>"${OUTTO}" 2>&1;` so I was expecting to see certain changes reflected there that were not. So i was not understanding why my edits were not being shown there.

Now I understand the difference I can edit and test my scripts,
