### ISSUE TITLE
Add new software

### ISSUE THREAD

**Issue by JuezFenix** [QuickBox/QB#39]
Can be a good idea to include this software:

Netdata
Flood
Webmin
Mktorrent webui
Mylar
Lazy Librarian
Autosub
Virtualbox webui

Many thanks.

**Comment by JMSDOnline** [comment]
We don't take requests via Github. Please open your request [on the forums](https://plaza.quickbox.io/c/suggestions-feedback). I can say for certain that I will not be adding Webmin ever as there is simply no need.
