### ISSUE TITLE
DWSALT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) runs forevers

### ISSUE THREAD

**Issue by deadbird99** [QuickBox/QB#50]
Hi.

I'm setting up Quickbox on a LXC container ran by Proxmox. Of course, I use Ubuntu 16.04.

The thing is, during deluge setup, this line runs forever:

    DWSALT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

Running

    cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1

in the Proxmox host successfuly returns a value. Doing the same in the container returns a value, but also loops forever.

**Comment by deadbird99** [comment]
BTW: this is line 686 of setup/quickbox-setup file.

**Comment by thomcuddihy** [comment]
Can confirm that this happens with QB installing into an Ubuntu 16.04 LXC container on Proxmox VE 5.1 host.

Change the `cat` to `head` to get it to salt properly and finish install.

**Comment by thomcuddihy** [comment]
Pull request submitted
