### ISSUE TITLE
Sabnzbd 2.2.0

### ISSUE THREAD

**Issue by danjames92** [QuickBox/QB#54]
Used the install script, it installed 2.2.0. **2.1.0** is working on another server and has been for a long while. On a new install, 2.2.0 throws an error when adding an host (host uses TLSv1.2).

Same OpenSSL 1.0.2g.
Same Python version.
I'm running Ubuntu 16.04.3 LTS.

![chrome_2017-08-11_18-13-08](https://user-images.githubusercontent.com/16107603/29224141-f1cf56c4-7ec0-11e7-94a2-c8ab01e18fc7.png)
No firewall enabled either. Any idea for what I can try?
Could it be related to this?
Is anyone running 2.2.0 successfully?
(https://github.com/sabnzbd/sabnzbd/issues/994)

**Comment by sanderjo** [comment]
So: news-de.newsgroup.ninja gives "Invalid server details"?

Uncheck SSL and try again. I don't think that is the cause, so we want to rule that out first.

**Comment by danjames92** [comment]
Tried without. Same issue.

**Comment by danjames92** [comment]
I'd just like to point out I've ordered an additional IP for a reverse proxy setup I'm planning to install so maybe this has something to do with it.

**Comment by sanderjo** [comment]
> Yes. I've tried other server addresses for newsgroup ninja too.
Tried without. Same issue.

Strange. What if you fill out newszilla.xs4all.nl (without SSL), and try?

**Comment by danjames92** [comment]
@sanderjo Same issue.

**Comment by sanderjo** [comment]
FWIW: this is the SAB code from `sabnzbd/utils/servertests.py`  that gives the error message:
```
    try:
        s = Server(-1, '', host, port, timeout, 0, 0, ssl, ssl_verify, False, username, password)
    except:
        return False, T('Invalid server details')
```
So the Server() command gives an exception. Very weird. I think a problem on your machine.

Can you `cd` into the directory that contains  the sabnzbd directories. On my Ubuntu:
```
sander@Stream-13:~/git/sabnzbd$ cd /usr/share/sabnzbdplus/
```
and then
```
sander@Stream-13:/usr/share/sabnzbdplus$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import sabnzbd.utils.servertests
>>> 
>>> dir(sabnzbd.utils.servertests)
['NewsWrapper', 'Server', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'clues_login', 'clues_too_many', 'get_servers', 'int_conv', 'nntp_to_msg', 'select', 'socket', 'sys', 'test_nntp_server', 'test_nntp_server_dict']
>>> 
>>> sabnzbd.utils.servertests.Server(-1, '', 'newszilla.xs4all.nl', 564, 10, 0, 0, False, False, False, 'bla', 'bla')
newszilla.xs4all.nl:564
>>> 
>>> 
```

**Comment by danjames92** [comment]
@sanderjo not quite sure I understand.

 I can get to home/user/SABnzbd/

then run 'python' and 'import sabnzbd.utils.servertests'

After than I'm lost with what you are asking me to do? :)

can you list the commands you want me to run individually?

**Comment by sanderjo** [comment]
Ah, yes, 563, although it doesn't matter for this call.

after the  'import sabnzbd.utils.servertests', still within python, do this:

```
dir(sabnzbd.utils.servertests)
sabnzbd.utils.servertests.Server(-1, '', 'newszilla.xs4all.nl', 563, 10, 0, 0, False, False, False, 'bla', 'bla')

```
Post the full output here, including the earlier commands.

**Comment by danjames92** [comment]
@sanderjo dont worry, will the help of some kind people i downgraded to 2.1.0. works fine.

2.2.0 does not.

I guess there's a bug in the script to install somewhere or in 2.2.0 beta.

**Comment by lizaSB** [comment]
It's not so much a bug as an oversight. The clone command doesn't specify a branch so it pulls the default one, which the developers of sab have happened to have set as the dev branch, not the stable branch.

**Comment by danjames92** [comment]
Seems like a prerelease bug with Sab. With the upgradeSAB command now it should be fine in the future. Closing as now works.
