### ISSUE TITLE
Box Not Start APACHE - SSL?

### ISSUE THREAD

**Issue by kanenses** [QuickBox/QB#56]
error from - systemctl status apache2.service
Aug 18 03:02:01 domain.info apache2[1262]: Output of config test was:
Aug 18 03:02:01 domain.info apache2[1262]: [Fri Aug 18 03:02:01.362645 2017] [so:warn] [pid 1272] AH01574: module proxy_modul
Aug 18 03:02:01 domain.info apache2[1262]: AH00526: Syntax error on line 40 of /etc/apache2/sites-enabled/default-ssl.conf:
Aug 18 03:02:01 domain.info apache2[1262]: SSLCertificateFile: file '/etc/ssl/certs/ssl-cert-snakeoil.pem' does not exist or
Aug 18 03:02:01 domain.info apache2[1262]: Action 'configtest' failed.
Aug 18 03:02:01 domain.info apache2[1262]: The Apache error log may have more information.
Aug 18 03:02:01 domain.info systemd[1]: apache2.service: Control process exited, code=exited status=1
Aug 18 03:02:01 domain.info systemd[1]: Failed to start LSB: Apache2 web server.
Aug 18 03:02:01 domain.info systemd[1]: apache2.service: Unit entered failed state.
Aug 18 03:02:01 domain.info systemd[1]: apache2.service: Failed with result 'exit-code'.
add journalctl -xe
Aug 18 03:02:01 domain.info systemd[1]: apache2.service: Unit entered failed state.
Aug 18 03:02:01 domain.info systemd[1]: apache2.service: Failed with result 'exit-code'.
Aug 18 03:02:01 domain.info sudo[1259]: pam_unix(sudo:session): session closed for user root
Aug 18 03:02:01 domain.info CRON[1277]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 18 03:02:01 domain.info CRON[1278]: (root) CMD (bash /usr/local/bin/quickbox/system/set_interface)
Aug 18 03:02:01 domain.info CRON[1277]: pam_unix(cron:session): session closed for user root
Aug 18 03:03:01 domain.info CRON[1288]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 18 03:03:01 domain.info CRON[1289]: (root) CMD (bash /usr/local/bin/quickbox/system/set_interface)
Aug 18 03:03:01 domain.info CRON[1288]: pam_unix(cron:session): session closed for user root
Aug 18 03:04:01 domain.info CRON[1296]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 18 03:04:01 domain.info CRON[1297]: (root) CMD (bash /usr/local/bin/quickbox/system/set_interface)
Aug 18 03:04:01 domain.info CRON[1296]: pam_unix(cron:session): session closed for user root 

anyhelp please :-)

**Comment by kanenses** [comment]
I try install lets encrypt, and get missing sal cert, as with self signed

I try comment server host certs até vhost, apache start but nothing, get not connect on browser Windows.

OS: UBUNTU 16.04.3 LTS x64
Host provide: servdiscount

Thank you


_Sent from my Asus ASUS_X00AD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by danjames92** [comment]
You need to setup letsencrypt first before cloudflare. remove the site from cloudflare and wait a bit.

box remove letsencrypt
reboot
box install letsencrypt

then it should be ok?

**Comment by danjames92** [comment]
Regardless....

Box remove letsencrypt 

Reboot

Box install letencrypt 

Follow instructions.

**Comment by danjames92** [comment]
Also sounds like you need to edit your ssl conf, check the github for the config and replace the snake oil line.

**Comment by kanenses** [comment]
@danjames92 for some reason after run box install letsencrypt, the remove command respond: package not found.
 :-(

**Comment by kanenses** [comment]
@danjames92 
In fact, my sal conf not contain as default file as here:
SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem

SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

My as Little different, looks as:
/etc/apache2/ssl-cert-snakeoil.key

Can be this reason!?

But after run box letsencrypt, still not working :-(

**Comment by danjames92** [comment]
You want to edit your file back to this...

https://github.com/QuickBox/QB/blob/master/setup/templates/default-ssl.conf.template

**Comment by kanenses** [comment]
@danjames92 Will give a try... Do you think will correct issue with letsencrypt too!?

**Comment by kanenses** [comment]
I have reinstall from scratch and follow the default-ssl.conf, its not working :-(
any idea please?

Thank you

**Comment by kanenses** [comment]
I have try alot of things nothing to be working :-( I have noted now that .config folder under my user not exist, it seems to me, is a issue with quickbox and distro os by servdiscount :-(
