### ISSUE TITLE
[Bug] Repo activity dies

### ISSUE THREAD

**Issue by danjames92** [QuickBox/QB#67]
Been seeing this on a fairly regular basis recently, comes and goes, not sure how to troubleshoot.

![firefox_2017-09-07_19-11-45](https://user-images.githubusercontent.com/16107603/30178335-7379fc52-9400-11e7-8263-262034862add.png)

**Comment by JMSDOnline** [comment]
Hey there @danjames92, this isn't so much a bug as it is an limit on the GitHub API.
