### ISSUE TITLE
Add desc to flush cache

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/QB#7]
To prevent user inquiry/issues, let's add a notice in the themes dropdown menu, with something along the lines of "For changes to theme to be applied, flush browser cache".

**Comment by KarmaPoliceT2** [comment]
Would this be the preferred route? or would turning off caching altogether on the page be the better route? I could understand either way...

**Comment by d2dyno** [comment]
@KarmaPoliceT2 for the amount of data that's displayed on the dashboard, I think cache would be best? Though I don't have the final say.

**Comment by KarmaPoliceT2** [comment]
This was merged into dev last night, give it a try and see if this resolves your concern.

**Comment by d2dyno** [comment]
Yes, excellent work!
