### ISSUE TITLE
Most widgets don't charge data after last update

### ISSUE THREAD

**Issue by JuezFenix** [QuickBox/QB#74]
After update from 2 o 3 commit, the ram, systime, disk, addicional brandwitch and recent activity widget dont show any data.

**Comment by JMSDOnline** [comment]
Run the update once more. There was a large change in the setup to ease those interested in contributing into it. It may require you to update twice... just to sticky the changes.

**Comment by JuezFenix** [comment]
Totally extrange, but works perfettly. Many thanks for speed solution.
