### ISSUE TITLE
Why Ubuntu, but not Debian ?

### ISSUE THREAD

**Issue by tianalemesle** [QuickBox/QB#83]
Hi,

I use Debian 8.9 on my VPS, and I would like to install QuickBox on it, but I can't because you decided to not support it, why ?

Ubuntu is based on Debian, so why you wouldn't support Debian if you support Ubuntu ?

Thanks.

**Comment by sachaw** [comment]
Look at the structure of the application, setup script and dependencies. Then make a judgement on whether it is/can be supported.

**Comment by tianalemesle** [comment]
Sorry, I don't have enough knowledge to make a judgement on this. Could you give me a hint ? Thanks !

**Comment by Qwatuz** [comment]
Because it's more work modifying something for another OS version. Why don't you just use an OS that's supported?

**Comment by tianalemesle** [comment]
Because I already have installed and setup a few web servers and services on my VPS before I saw that the tutorial I read about QuickBox is outdated enough to not say that you're not supporting Debian anymore.
I also looked for a solution to migrate from Debian to Ubuntu without complete re-configuration, but I didn't found anything like that.
And finally, I don't know enough about Ubuntu on servers if I have a problem with it.
Thanks.

**Comment by tianalemesle** [comment]
I finally decided to re-install my VPS with Ubuntu 16.04 and I successfully installed QuickBox.

Now, I have multiple problems :

- ruTorrent is saying : « No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file. »
- NextCloud is asking for database configuration, but I can't access PHPMyAdmin (access denied for root and admin)
- pyLoad is saying 503 Service Unavailable
- There is "Index of /admin.rtorrent.downloads" instead of h5ai
- Disk status on dashboard is not showing any value
- In SSH, I can't clear properly terminal on screen sessions, even with reset command (but there is no such problem on Web Console)

However, they seems to work :
- Dashboard
- Emby
- Web Console

Could you help me, please ?

Thank you for your work and your time. ;)

**Comment by JMSDOnline** [comment]
Real quick, the issue tracker is not a support line. Please use our forums at https://plaza.quickbox.io for these enquiries. Additionally, check the wiki on quickbox.io for a list of QuickBox commands, you more than likely didn't finish the setup for pyload. Nextcloud doesn't use phpmyadmin, you generate these credentials on install. Finally, visit the forums and remember search is your friend. You'll get far more effort for support there if you put forth a small amount yourself 😃

**Comment by tianalemesle** [comment]
I understand, but is there any tutorial available for complete A-Z installation of every component ? Thanks.

**Comment by sachaw** [comment]
For future use, it is desirable to host QB on its own is with nothing else for comparability and performance reasons, hence virtualising it on your VPS is a great idea
