### ISSUE TITLE
ruTorrent connection problem & QB Website Down

### ISSUE THREAD

**Issue by fightmaxime** [QuickBox/QB#86]
ruTorrent : Tracker: [Unable to connect to UDP tracker.]
Website : Error 502 Ray ID: 3a937f28bfbd3fa7 • 2017-10-05 21:32:59 UTC
Bad gateway

**Comment by JMSDOnline** [comment]
I'm aware the website is down. We had a raid controller go bad and I'm hoping to have the site back up tonight.
