### ISSUE TITLE
Updated QuickBox- no CPU/DISK/RAM/TORRENT data

### ISSUE THREAD

**Issue by antigravity83** [QuickBox/QB#88]
Hey there

As per title- I ran the update script, and no longer have CPU/DISK/RAM/TORRENT data

Any help would be great

Thanks

**Comment by rex099** [comment]
Totally not sure if this is the same as my issue but i tend to have that happen after an update as well, then after a few page refreshes it starts displaying again. Also you could try clearing web cache to make sure something just didn't get messed up there.

**Comment by antigravity83** [comment]
Like you said, it ended up sorting itself out. Thanks anyway :+1:
