### ISSUE TITLE
Make header menu responsive on mobile

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/QB#9]
Right now the ".headermenu > li " does not scale for mobile, so you end up with menu items out of their element, over the BW graph.

Screenshot of issue:
![quickbox dashboard](https://cloud.githubusercontent.com/assets/2421939/25316878/e13048d4-2833-11e7-93e1-634d243de2ef.png)

**Comment by JMSDOnline** [comment]
I'm going to review this one today as I am building database structure. Seems a good a time as any.

**Comment by JMSDOnline** [comment]
Built in a better menu as per this commit a796b0c2644c483600b4ee44b340387d671fa7b9 .

### Desktop
![2017-09-11_16-39-39](https://user-images.githubusercontent.com/16356910/30298193-19e32606-9710-11e7-86fb-418a67dccdfd.gif)

### Mobile (theoretically, haven't it truly tried it on mobile yet)
![2017-09-11_16-41-32](https://user-images.githubusercontent.com/16356910/30298235-3ae6a896-9710-11e7-88cc-fdb1ef2b42a9.gif)

**Comment by d2dyno** [comment]
Tested from mobile, the issue is fixed. Thanks!
