### ISSUE TITLE
Having some trouble on the package installation

### ISSUE THREAD

**Issue by HiImSinak** [QuickBox/QB#90]
Hi there !

I'm currently blocked on my QuickBox server.

Actually I can not use any package software like Sonarr or Jackett.

![capture d ecran de 2017-10-13 12-07-35](https://user-images.githubusercontent.com/11378640/31541536-4562f096-b00f-11e7-8514-31ccc2d02740.png)

It's the result when i'm clicking on the Jackett application from the QuickBox Dashboard.

I hope some help.

Best Regards
hiimsinak

EDIT: I'm running the QB server on Ubuntu 16.04 server.

**Comment by alex7614** [comment]
Hi

Yesterday same problem with Jackett and rTorrent with 4 fresh Ubuntu 16.04.03 on Esxi 6.5

After 5 re-install, it's working....

**Comment by HiImSinak** [comment]
I re-installed it 3 times actually. 

I'm pretty disappointed. I'm on Proxmox

**Comment by alex7614** [comment]
Have you check the install log in /root ?

Maybe it indicate the problem.

For me, and for win time, I installed fresh Ubuntu 16.04.03, ssh, snapshot (no apt upgrade before QuickBox install).
So when the install was corrup, revert snapshot and reinstall...

And the last 5th install, no problem...
But for me, i didn t check the install log.

**Comment by JMSDOnline** [comment]
Well, the link for Jackett is actually `https://<serverip>/jackett/UI/Dashboard`. Not sure how you're getting `https://<serverip>/jackett/`.

1. Can you access Jackett via `http://<serverip>:9117/jackett`?
2. What does your **/etc/apache2/sites-enabled/jackett.conf** look like?
3. What is the output of `systemctl status jackett@<username>` ?

Additionally, Proxmox has been an issue in the past. I'll need to mess with an install on Proxmox to confirm any lingering issues.

**Comment by HiImSinak** [comment]
Hi guys and thanks for those answers.

My mistake, the correct url was this one : 
![capture d ecran de 2017-10-13 16-04-37](https://user-images.githubusercontent.com/11378640/31550114-86e03aa8-b030-11e7-8311-4525f06c23b1.png)


I'm going to try your different steps. Thanks

**Comment by HiImSinak** [comment]
So, I tried your advice : 

1)http://<myserverip>:9117/jackett doesn't work.

2)The jacket conf is like this : 
![capture d ecran de 2017-10-13 16-10-50](https://user-images.githubusercontent.com/11378640/31550344-5d7b4f12-b031-11e7-8d83-347cad756dd6.png)

3) The command result : 
![capture d ecran de 2017-10-13 16-14-03](https://user-images.githubusercontent.com/11378640/31550441-a3f9c3f6-b031-11e7-8595-cb0e155efb3b.png)

Best Regards

**Comment by alex7614** [comment]
Hi

Ubuntu 16.04.03 CD 1 
vSphere 6.5 U1

Ubuntu -> Fresh install with only OPENSSH-SERVER
Package upgrade during Installation of Ubuntu from French REPO.

**Comment by HiImSinak** [comment]
@alex7614 , can you pm me in private ? I think you're french.

The issue is still the same currently. I'm disapointed.

**Comment by JMSDOnline** [comment]
Not so sure what you're "disappointed" about. This seems to be an isolated instance as it installs without issue on several servers I have ran this on. Here is a snapshot of this morning on a local install.

![chrome_2017-10-27_11-06-25](https://user-images.githubusercontent.com/16356910/32113954-90d415ca-bb07-11e7-920c-c029fb6a4d01.png)

Have you made certain these modules are installed?

`a2enmod proxy` 
`a2enmod proxy_http`

Followed by `service apache2 restart`

You could additionally try changing your `jackett.conf` to the following:
```
RequestHeader set X-Forwarded-Proto "https"
<Location /jackett>
ProxyPass http://localhost:9117/jackett
ProxyPassReverse http://localhost:9117/jackett
Require all granted
</Location>
```

Again, this could be ann issue with your Proxmox. Have you tried an install without Proxmox?

**Comment by dtech4you** [comment]
could be that when installed he used a public ip and or a invalid ip when setting up the app so that it does not use the localhost and not using the reverse proxy correctly
