### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by echersdk** [QuickBox/QB#95]
Hi.

As you most likely are well aware, the site is currently down.
Therefore I cannot search the forums for information about how to fix a few of my issues.

I made a post a 1-2 days ago related to som SSH issues after following the permissionsguide for PLEX.
I fixed this somehow by trying multiple things. Dunno which one was the fix.

But now I suddently cannot see the ruTorrent image in the menubar of the webui, and my Deluge link only loops back to the webui, thus not loading the Deluge UI at all.

I did try and follow the guide on the forums for the rutorrent image in the menubar, but everything seems to be in order according to that thread. rtorrent.lock file in correct location etc.

See this image to see the menu bar on my webui:
https://i.imgur.com/T8HHLbC.png

How do I go about getting the ruTorrent image back and Deluge working?

Lastly, I seem to have lost access to the "Downloads" part of the webui both for ruTorrent and Deluge:
https://i.imgur.com/zyYP3s8.png

Thank you in advance for your assistance.

**Comment by dannycorker** [comment]
I set up a new install yesterday, and every one of my links from the menu bar now times out, aside from plex which is on its own subdomain. Seeing the same on a server set up a few days ago which was working fine.

I didn't expect the quickbox site going down to affect my access to services once I was hosting?

**Comment by goodpunk6** [comment]
Can confirm, since the site went down, I barely have any access to my server. Seems like I can't even login anymore.

**Comment by OrgoSteph** [comment]
I haven't seen any type of announcement on why the website went down either. Really odd.

**Comment by echersdk** [comment]
I'm not really the patient type of person... Therefore I wiped my server and installed swizzin instead which is supported much better, runs much smoother and is simply an optimized fork of QB. It's a former developer of QB who also got impatient with the lead dev of QB.

Don't get me wrong... The idea behind QB is GREAT, just not maintained properly.

So yeah, check out swizzin

**Comment by OrgoSteph** [comment]
I have no problem with Quickbox right now. Everything is running smoothly for me. If it ever gets to the point that it stops working. I will move over, but for now, I am chugging along.

**Comment by echersdk** [comment]
@OrgoSteph
For me that simply wasn't an option, when I couldn't get any assistance and my server most definately wasn't running smoothly.

Luckily we all experience different thing :-)

**Comment by OrgoSteph** [comment]
Yeah I am glad you found something else to fit your needs. 

And I am with you Quickbox needs to be maintained differently if they want to survive.

**Comment by JMSDOnline** [comment]
The site is coming back up today. I am typically pretty busy during the week, therefore, it's hard for me to put in extra amounts of time for writing up announcements. Once again, we had a server failure and are working out an arrangement with Seedbox.io (whom will sponsor us).

Those of you saying that you have no access to your servers since the site went down are grasping at straws. The code-base of QuickBox has zero to do with the website being online. Additionally, others saying they are upset at the lack of support... well, you're using a free software. I need to get the site back online before I can pour hours into support. This isn't meant as a snide remark, merely a note on the way things currently are. 

I should have a server delivered today for getting the site back online.

Again, the site has nothing at all to do with your server installs.

**Comment by OrgoSteph** [comment]
@JMSDOnline Thanks for the update!

I have ran community based websites in my free time and also for work. The two best things I have ever done was twitter and a statuspage. A quick response saying "website is down, be back up in X amount days check for updates on twitter." or something like that goes a long way. It lets people know you are working to get it back up, and keeps the rumors down "are they dead?" type of stuff. 

Take care

**Comment by Vach0n** [comment]
> The two best things I have ever done was twitter and a statuspage. A quick response saying "website is down, be back up in X amount days check for updates on twitter." or something like that goes a long way. It lets people know you are working to get it back up, and keeps the rumors down "are they dead?" type of stuff.

I couldn't agree more!
It is so important to let the community and/or customers know about the state, when things go down.

The minute you knew the site went down, a simple update here (or as mentioned, on Twitter) would help alot.

Could've said:
>We are currently experiencing some issues with our webhost and are working to resolve the issue... Hang in there.

Or something like that :)

**Comment by echersdk** [comment]
@JMSDOnline 
Why did you mark the issue as closed, when neither of the two issues mentioned in OP has been fixed?

**Comment by JMSDOnline** [comment]
I actually didn't mean to mark the issue as closed. I am currently working on restoring the backups on the new server and getting all this up as quickly as possible.

@Vach0n, I agree with you. However, I also work 10 to 14 hour days and the site going down was a surprise to me. Handling additional social media outlets is something that I simply don't have time for at the present. 

Not trying to let you guys down here, I'm just getting dealt a bad hand lately it seems. Issues like this tend to slow down both development and support. I do appreciate a bit of patience and I do apologize for the lack of communication, but I really appreciate your understanding. I'll address the main issue at hand with this once I get things back up... priorities. 👍

**Comment by dtech4you** [comment]
now that site is back up and running i think it's safe to close this thread. if i am wrong oh well XD
